### PR TITLE
Set lower bound for scipy version in python 3.8

### PR DESCRIPTION
**Pull request by HenKlei**
See https://github.com/pymor/pymor/pull/1871

### CODE REVIEW

**Comment by renefritze** [comment]
I think `<1.21` is too restrictive. `<1.24` should be enough.

**Comment by renefritze** [comment]
Also, you sure that the problem isn't the lower bound? The error comes from the "oldest" job, no?

**Comment by HenKlei** [comment]
> Also, you sure that the problem isn't the lower bound? The error comes from the "oldest" job, no?

I think pinning scipy to `scipy>=1.6.3` could also be an option. What would you prefer?

**Comment by renefritze** [comment]
Yeah, I'd say scipy

**Comment by HenKlei** [comment]
> Yeah, I'd say scipy

Okay, that's also what I wanted to try right now.

**Review by renefritze — APPROVED** [review]
It's actually not a big change at all with py 3.9 already pinning 1.5

**Pull request merged**
